### ISSUE TITLE
Retrieve all species with aw_data

### ISSUE THREAD

**Issue by mpnelsen** [ropensci/AntWeb#18]
Hi,

I have been using aw_distinct to retrieve the names of species in certain groups, but was noticing some discrepancies between taxa retrieved and what is listed on AntWeb.  It seems as though taxa lacking specimens are not retrieved.  Is it possible to also retrieve the names of species that lack specimens?  For instance, a search for species in Dorylus:

require("AntWeb")
dorylus<-aw_data(genus="Dorylus")
sort(unique(dorylus$data$scientific_name))

This does not seem to retrieve Dorylus atratus or Dorylus bishyiganus, which seem to be included in Dorylus (as a valid taxon) in AntWeb and AntCat:
https://www.antweb.org/browse.do?subfamily=dorylinae&genus=dorylus&rank=genus&project=worldants
http://antcat.org/catalog/436753
http://antcat.org/catalog/436761

Thanks much for your help.

-Matt

**Comment by karthik** [comment]
Thanks for the note, @mpnelsen 
I'lll look into it and report back.

**Comment by mpnelsen** [comment]
Thanks so much, @karthik

**Comment by mpnelsen** [comment]
Hi @karthik - I think it might be an issue on the AntWeb API side of things, not with the AntWeb R package, so we can close this if you agree.  I've contacted them about this.  Thanks.

**Comment by karthik** [comment]
THanks @mpnelsen Makes sense. Please update this thread if you don't hear from them. I know the folks behind AntWeb and also the developer who maintains the API.
