### ISSUE TITLE
*aw_data* error

### ISSUE THREAD

**Issue by tsrsilva** [ropensci/AntWeb#24]
Greetings

I've been trying to retrieve AntWeb data using aw_data, but keep getting a fromJSON and an HTTP 404 error:

**Example**

`data <- aw_data(genus = 'Strumigenys', species = 'cultrigera')`

**Execution and error**

> data <- aw_data(genus = 'Strumigenys', species = 'cultrigera')`
Error in fromJSON(content(results, "text")) : unexpected character '<'
In addition: Warning message:
In aw_data(genus = "Strumigenys", species = "cultrigera") :
  Not Found (HTTP 404).

I believe that the function is trying to use the base_url of a deprecated API version to query data.

**System Info**

 $ platform      "x86_64-w64-mingw32"
 $ arch             "x86_64"
 $ os                "mingw32"
 $ system         "x86_64, mingw32"
 $ status           ""
 $ major           "3"
 $ minor           "6.0"
 $ year              "2019"
 $ month          "04"
 $ day               "26"
 $ svn rev          "76424"
 $ language      "R"
 $ version.string"R version 3.6.0 (2019-04-26)"
 $ nickname      "Planting of a Tree"

**Package Info**

Package: AntWeb
Version: 0.7
Depends: R (>= 3.0.1)
Imports: rjson, plyr, assertthat, httr, leafletR (>= 0.1-1)
Built: R 3.6.0; ; 2019-06-02 00:44:19 UTC; windows

**Comment by karthik** [comment]
Hi @tsrsilva, I just recently learned that Brian from Cal Academy, who maintains this resource, has shut down the servers. Hence the 404. I will confirm with him and then update the thread. Unfortunately it will also mean an end to this package.

**Comment by tsrsilva** [comment]
Hello @karthik thank you for replying. 
So sorry to hear that. The package was extremely useful and easy to work with. Thank you for making such an amazing tool.
